#!/bin/sh

set -e

case "${1}" in
	configure)
		if ! dpkg-statoverride --list /bin/fusermount > /dev/null 2>&1
		then
			chmod 4755 /bin/ntfs-3g
		fi

		if [ -x /usr/sbin/update-initramfs ]
		then
			update-initramfs -u
		fi
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

# Automatically added by dh_makeshlibs
if [ "$1" = "configure" ]; then
	ldconfig
fi
# End automatically added section


exit 0
