#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
    update-alternatives --install /usr/bin/x-terminal-emulator \
        x-terminal-emulator /usr/bin/roxterm 50 --slave \
        /usr/share/man/man1/x-terminal-emulator.1.gz x-terminal-emulator.1.gz \
        /usr/share/man/man1/roxterm.1.gz
fi

# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section


exit 0
