# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.browsewithcaret", true);
user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1451090244);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1451090364);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1451112759);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1451090124);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1451113874);
user_pref("browser.cache.disk.capacity", 245760);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "/root");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.save_converter_index", 1);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.search.countryCode", "CN");
user_pref("browser.search.region", "CN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20151104080838");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage", "www.baidu.com");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3}");
user_pref("browser.tabs.warnOnClose", false);
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_TOOLBOX_OPENED_PER_USER_FLAG\":\"38.4.0\",\"DEVTOOLS_WEBCONSOLE_OPENED_PER_USER_FLAG\":\"38.4.0\"}");
user_pref("dom.max_script_run_time", 0);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 7);
user_pref("extensions.blocklist.pingCountVersion", 7);
user_pref("extensions.bootstrappedAddons", "{\"langpack-zh-CN@iceweasel.mozilla.org\":{\"version\":\"38.4.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-zh-CN@iceweasel.mozilla.org.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.4.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1451090249);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "38.4.0");
user_pref("extensions.lastPlatformVersion", "38.4.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-zh-CN@iceweasel.mozilla.org\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/langpack-zh-CN@iceweasel.mozilla.org.xpi\",\"e\":true,\"v\":\"38.4.0\",\"st\":1446600005000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.4.0\",\"st\":1448159803000,\"mt\":1446631805000}}}");
user_pref("gecko.buildID", "20151104080838");
user_pref("gecko.mstone", "38.4.0");
user_pref("idle.lastDailyNotification", 1451091194);
user_pref("media.gmp-manager.buildID", "20151104080838");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1449965159);
user_pref("places.history.expiration.transient_current_max_pages", 15420);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("plugin.soname.list", "");
user_pref("pref.privacy.disable_button.view_passwords", false);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.disable_button.openCertManager", false);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1448161894);
user_pref("toolkit.startup.last_success", 1451114412);
user_pref("toolkit.telemetry.previousBuildID", "20151104080838");
