#!/bin/sh

# Prints "Moo" using every font installed on /usr/share/figlet
# Written by Sandro Tosi <matrixhasu@gmail.com>
# Modified by Jonathan McCrohan <jmccrohan@gmail.com>

for file in /usr/share/figlet/*.flf ; do 
  FONT=`basename $file | sed 's|\(.*\)\.\(.*\)|\1|'`

  printf "Font: $FONT\n"
  figlet -f $FONT Moo
  printf "\n"
done
