#!/bin/bash

for file in /usr/share/cli-common/runtimes.d/*
  do	
  if [ -x $file ]; then
      # Figure out the formal name
      F="$($file name)"

      # Remove it
      echo "Removing $1 from $F"
      $file remove $1
  fi
done
